# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161228_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
